# this workflow is mainly a demo of how you can use the script/tarball command to create a tarball of the repo/project
# adapt this to your own needs

name: tarball

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tarball:
    name: tarball
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 # pin@v1.254.0
        with:
          bundler-cache: true

      - name: tarball
        run: script/tarball

      - name: tarball test
        run: spec/acceptance/tarball-test
